// Code generated by "stringer -type=MacroName"; DO NOT EDIT.

package main

import "strconv"

const _MacroName_name = "AfmuRepairsApproachSettlementBountyBuyAmmoBuyDronesCargoChangeCrewRoleCollectCargoCommitCrimeCommunityGoalCommunityGoalJoinCommunityGoalRewardCrewAssignCrewFireCrewHireCrewLaunchFighterCrewMemberJoinsCrewMemberQuitsCrewMemberRoleChangeDatalinkScanDatalinkVoucherDataScannedDiedDockedDockFighterDockingCancelledDockingDeniedDockingGrantedDockingRequestedDockSRVEjectCargoEndCrewSessionEngineerApplyEngineerContributionEngineerCraftEngineerProgressEscapeInterdictionFactionKillBondFetchRemoteModuleFileheaderFriendsFSDJumpFuelScoopHeatDamageHeatWarningHullDamageInterdictedInterdictionJetConeBoostJoinACrewLaunchFighterLaunchSRVLiftoffLoadGameLoadoutLocationMarketBuyMarketSellMassModuleStoreMaterialCollectedMaterialDiscardedMaterialDiscoveredMaterialsMiningRefinedMissionAbandonedMissionAcceptedMissionCompletedMissionFailedMissionRedirectedModuleBuyModuleRetrieveModuleSellModuleSellRemoteModuleStoreModuleSwapMusicNavBeaconScanPassengersPayFinesPayLegacyFinesPowerplayCollectPowerplayDeliverPowerplayFastTrackPowerplayLeavePowerplaySalaryProgressPromotionQuitACrewRankRebootRepairReceiveTextRedeemVoucherRefuelAllRepairRepairAllRepairDroneRestockVehicleResurrectScanScannedScreenshotSearchAndRescueSellDronesSellExplorationDataSendTextSetUserShipNameShieldStateShipyardBuyShipyardNewShipyardSellShipyardSwapShipyardTransferStartJumpSupercruiseEntrySupercruiseExitSynthesisTouchdownUndockedUSSDropVehicleSwitchWingAddWingInviteWingJoinWingLeaveNO_JEVENT"

var _MacroName_index = [...]uint16{0, 11, 29, 35, 42, 51, 56, 70, 82, 93, 106, 123, 142, 152, 160, 168, 185, 200, 215, 235, 247, 262, 273, 277, 283, 294, 310, 323, 337, 353, 360, 370, 384, 397, 417, 430, 446, 464, 479, 496, 506, 513, 520, 529, 539, 550, 560, 571, 583, 595, 604, 617, 626, 633, 641, 648, 656, 665, 675, 690, 707, 724, 742, 751, 764, 780, 795, 811, 824, 841, 850, 864, 874, 890, 901, 911, 916, 929, 939, 947, 961, 977, 993, 1011, 1025, 1040, 1048, 1057, 1066, 1070, 1082, 1093, 1106, 1115, 1121, 1130, 1141, 1155, 1164, 1168, 1175, 1185, 1200, 1210, 1229, 1237, 1252, 1263, 1274, 1285, 1297, 1309, 1325, 1334, 1350, 1365, 1374, 1383, 1391, 1398, 1411, 1418, 1428, 1436, 1445, 1454}

func (i MacroName) String() string {
	if i >= MacroName(len(_MacroName_index)-1) {
		return "MacroName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MacroName_name[_MacroName_index[i]:_MacroName_index[i+1]]
}
