#+TITLE: BC+ – BoardComputer+ Dokumentation

* Download
[[https://github.com/CmdrVasquess/BCplus/releases][Binary Downloads]] findet man auch auf Github. Die „Basisversion“ ist
unter =BCplus-<version>.zip= zu finden. Sobald ich von dieser Version
auch eine lokalisierte, deutsche Fassung habe wird die dort auch unter
=BCplus-de-<version>.zip= zu finden sein.

* Installation
BC+ wird z.Z. nur für den Win-PC gebaut. Um es laufen zu lassen werden
keine zusätzlichen Laufzeitumgebungen benötigt. Auch kommt BC+ ohne
Installation aus – man kann es direkt aus dem ausgepackten ZIP Archiv
laufen lassen. Das bedeutet

- Es gibt keine Berechtigungsprobleme wenn man BC+ installiert.

- Neue Versionen können einfach installiert werden, indem man den
  alten Ordner wegschmeißt und das neue ZIP Archiv
  auspackt. (Ggf. vewahrt man die alte Version erst mal…?!)

- Es werden aber auch keine Startmenü Einträge und Icons eingerichtet.

* Starten und Beenden
BC+ sollte gestartet werden, bevor E:D startet. BC+ beobachtet den
Ordner mit Journal Dateien und fängt an diese zu lesen, sobald eine
neue Datei angelegt wird (vgl. Startoption =-l= unten).

Für eine 08/15 E:D Installation aus dem Frontier Store reicht ein
Doppel-Klick auf die BCplus.exe. Diese findet automatisch alles
nötige:

- Den Ordner mit den E:D Journal Dateien

- Den Ordner, in dem BC+ seine Daten ablegt

Beides wird auch als Textnachricht im Konsole-Fenster angezeigt, wenn
BC+ startet. Wer keine 08/15 Installation hat, kann bzw. muss die
Pfade beim Start auf der Kommandozeile übergeben.

** Startoptionen für BC+
- -h :: Zeigt eine kurze Beschreibung der Startoptionen an.

- -j <ordner> ::  Setzt den Ordner, in dem E:D die Journal Dateien anlegt.

- -d <ordner> ::  Setzt den Ordner, in dem BC+ seine Dateien ablegt

- -l :: Liest nach dem Start die jüngste Journal Datei ein. Sonst
        wartet BC+ bis E:D beim Start die neue Journal Datei
        anlegt. (kann gut verwendet werden, wenn man BC+ bei laufendem
        Spiel startet)

- -p :: Setzt den Socket Port, auf dem BC+ auf HTTP Anfragen
        lauscht. Per Voreinstellung ist der Wert auf =1337=
        gesetzt. Wenn es hier zu Problemen kommt, bspw. weil ein
        anderes Programm diesen Port bereits belegt, kann eine andere
        Nummer 1024–65535 gewählt werden.

Weitere Optionen wird der „normale“ Anwender hoffentlich nicht nötig
haben. Wenn doch: =-h= hilft ein wenig weiter. Wenn das nicht reicht:
/Use the source, Luke!/

** Web Browser verbinden
Neben dem Konsole Fenster wird auf dem Computer mit E:D nicht viel
passieren. Die Idee ist ja, dass man einen Web Browser auf einem
anderen Computer nutzt, um die Web-GUI von BC+ anzuzeigen. Das
bedeutet aber auch, dass man dem Web Browser die „Seite“ (URL) nennen
muss, unter der BC+ zu finden ist. Weil der Computer mit E:D im
Heimnetzt steht passiert das vermutlich nicht über eine lesbaren
Domain Namen, wie z.B. =github.com=, sondern über die IP Adresse des
E:D Computers. BC+ versucht die richtige Adresse raus zu bekommen und
schreibt die Komplette URL als Vorschlag in das Terminal
Fenster. Z.B. =http://192.168.0.3:1337/=. Das sollte meistens
funktionieren. Wenn man aber einen Rechner mit mehreren Netz-Karten
oder mehreren IP Adressen hat, dann wirds komplizierter (als ich es
BC+ beigebracht habe) und Ihr müsst Euch (vorerst) selber kümmern.

Wenn der Browser einmal mit BC+ verbunden ist, sieht man solange den
„offline“ Bildschirm, bis BC+ aus der Journal Datei weiß, welcher
Kommandant geladen werden muss (Hier bitte ein Lesezeichen
anlegen). Dann schaltet BC+ in den „online“ Modus.

** BC+ Beenden
BC+ sammelt laufend Infos aus dem Journal. Einige dieser Informationen
sind im Journal nicht „leicht“ zu finden. – Beispiel: Beim Start
schriebt E:D immer den aktuellen Kontostand in das Journal. Also kann
BC+ die Info regelmäßig aus dem Laufenden Journal lesen. Im Gegensatz
dazu kann BC+ den Standort der Schiffe nicht finden, ohne alle
vorhandenen Journal Dateien zu durchsuchen. …Und deswegen merkt sich
BC+ den Standort der Schiffe wären die passenden Events zum Standort
im Journal auftauchen.

Damit diese und andere interessante Informationen nicht verloren
gehen, muss BC+ die Gelegenheit haben, diese Infos zu speichern. Und
weil ich – recht faul – die Daten nur gelegentlich speichere,
insbesondere beim /kontrollierten herunterfahren/ des BC+, ist es
wichtig, dass BC+ auch kontrolliert herunter gefahren wird.

Das bedeutet, dass man am einfachsten den „Aus“-Schalter in der Web
GUI verwendet. Man kann auch im Terminal Fenster Strg-C drücken, bis
man die Meldungen sieht, dass BC+ runter gefahren wird. Was man jedoch
*nicht machen* sollte ist, den Schließen Knopf [X] des Terminal
Fensters zu drücken!

** Ein Wort zur Sicherheit
Z.Z. verbindet sich BC+ über HTTP (ohne ‘S’). D.h. dass die
Netzkommunikation im Klartext in Eurem lokalen Netz läuft. In der
aktuellen Version werden keinen sensiblen Daten übertragen: Keine
Passworte, Bernutzerkennungen o.Ä. Von daher ist das meines Erachtens
im Augenblick Problem.

Aber während Ihr spielt und der BC+ läuft, können sich noch weitere
Web Browser mit dem BC+ verbinden und damit all das tun, was der
„eigentliche“ Nutzer auch tun kann. Bitte bedenken!

* Deinstallation
Braucht man nicht! Wer würde diese *unglaublich* nützliche Tool je
wieder deinstallieren wollen. Spaß bei Seite: Es reicht, wenn man 

1. den BCplus Ordner aus dem Download-ZIP und
2. den Ordner mit den eigenen BC+ Dateien (C:\Users\<user>\bcplus)
   löscht.

…Ach ja! Und das Lesezeichen aus dem Browser kann man auch noch
wegschmeißen ;)
