#+TITLE: BC+ – BoardComputer+ Documentation

* Download

[[https://github.com/CmdrVasquess/BCplus/releases][Binary Downloads]] can be found on github. The “basic” build, i.e. the
English version, is the file =BCplus-<version>.zip=. Othe language
packages may become available as =BCplus-<lang>-<version>.zip=.

* Installation
Currently BC+ is only build for the PC. To run BC+ no additional
runtime environment, like e.g. Python or Java, is needed. BC+ is
written in [[https://golang.org][Go]] and runs native on your machine. Further more BC+ is
written to run right out of the box without installation. This means

- New versions are easy to install. Simply delete the old BCplus
  folder and unzip the new one right in place. (May be you wanna keep
  the old version around until you are satisfied with the new one?)

- On the other hand no one creates nice start-menu entries or icons on
  the desktop for you.

* Running and Exit
BC+ should be started before running E:D. BC+ watches the journal
directory and starts reading when a new journal file is created (see
also option =-l=).

If you have a standard E:D installation from the Frontier Store simply
double-clicking BCplus.exe will do the job. BC+ should detect necessary
paths by itself:

- The E:D journal file folder

- The folder with BC+'s own data files

Both paths will be displayed in BC+ text console when it starts. If
you don't have the standard installation you have to set the paths on
the command line.

** Command Line Options
First, option syntax is not Windows standard – BC+ is written in [[https://golang.org][Go]]
and uses Go's standard command line parsing package. So be prepared to
start options with '-' not '/'.

- -h :: show help information, i.e. the complete and up-to-date list
        of options.

- -j <directory> :: set the path to the directory containig your
                    journal files.

- -d <directory> :: set the directory where BC+ collects data about
                    your commander and the visited galaxy (BC+ can
                    handle multiple commanders)

- -l :: pick up the lates journal file when starting. This is useful
        if you run BC+ after E:D already started to write the journal
        file.

- -p <port> :: set the port on which the web server is listening
               (default: 1337).

Normal users shouldn't need more options. If you feel that there has
to be more try =-h= to see the complete list of options. This should
help a little. If even that isn't enough: /Use the source, Luke!/

** Connecting the Web Browser

** Shutting Down BC+

** Few Word on Security
Currently BC+ serves its GUI over HTTP (without 'S'). This means that
data is send as clear text over you local network. Currently there is
no sensitive data transferred: No passwords, users ids etc. Thus HTTP
should be no problem for now.

However keep in mind that while BC+ is running any Web Browser in your
net can connect to it. Those user can perform same actions on BC+ as
you do! Keep this in mind.

* Uninstall
Is *absolutely* unnecessary! Who would ever delete such a useful,
nice, wonderful… OK, OK, OK. It's simple—just delete

1. the BCplus folder you unzipped from the download
2. the data folder (default: C:\Users\<user>\bcplus)°
3. any Browser bookmarks you created

That's it.
