// Code generated by "stringer -type=BodyCat"; DO NOT EDIT.

package galaxy

import "fmt"

const _BodyCat_name = "UnknownStarPlanet"

var _BodyCat_index = [...]uint8{0, 7, 11, 17}

func (i BodyCat) String() string {
	if i >= BodyCat(len(_BodyCat_index)-1) {
		return fmt.Sprintf("BodyCat(%d)", i)
	}
	return _BodyCat_name[_BodyCat_index[i]:_BodyCat_index[i+1]]
}
