// Code generated by "stringer -type MatCategory"; DO NOT EDIT.

package galaxy

import "strconv"

const (
	_MatCategory_name_0 = "RawManEnc"
	_MatCategory_name_1 = "Undef"
)

var (
	_MatCategory_index_0 = [...]uint8{0, 3, 6, 9}
)

func (i MatCategory) String() string {
	switch {
	case 1 <= i && i <= 3:
		i -= 1
		return _MatCategory_name_0[_MatCategory_index_0[i]:_MatCategory_index_0[i+1]]
	case i == 255:
		return _MatCategory_name_1
	default:
		return "MatCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
