// Code generated by "stringer -type PartType"; DO NOT EDIT.

package galaxy

import "strconv"

const _PartType_name = "StarPlanetBeltRingPort"

var _PartType_index = [...]uint8{0, 4, 10, 14, 18, 22}

func (i PartType) String() string {
	if i < 0 || i >= PartType(len(_PartType_index)-1) {
		return "PartType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PartType_name[_PartType_index[i]:_PartType_index[i+1]]
}
