// Code generated by "stringer -type statGuiFocus"; DO NOT EDIT.

package core

import "strconv"

const _statGuiFocus_name = "statNoFocusstatIntPanelstatExtPanelstatComPanelstatRolePanelstatStationSvcstatGalaxyMapstatSystemMap"

var _statGuiFocus_index = [...]uint8{0, 11, 23, 35, 47, 60, 74, 87, 100}

func (i statGuiFocus) String() string {
	if i < 0 || i >= statGuiFocus(len(_statGuiFocus_index)-1) {
		return "statGuiFocus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _statGuiFocus_name[_statGuiFocus_index[i]:_statGuiFocus_index[i+1]]
}
