// Code generated by "stringer -type=RankType"; DO NOT EDIT.

package cmdr

import "strconv"

const _RankType_name = "RnkCombatRnkTradeRnkExploreRnkImpRnkFedRnkCqcRnkCount"

var _RankType_index = [...]uint8{0, 9, 17, 27, 33, 39, 45, 53}

func (i RankType) String() string {
	if i < 0 || i >= RankType(len(_RankType_index)-1) {
		return "RankType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RankType_name[_RankType_index[i]:_RankType_index[i+1]]
}
