// Code generated by "stringer -type SlotKind"; DO NOT EDIT.

package cmdr

import "strconv"

const _SlotKind_name = "HardpointUtilityCoreModuleOptModule"

var _SlotKind_index = [...]uint8{0, 9, 16, 26, 35}

func (i SlotKind) String() string {
	i -= 1
	if i < 0 || i >= SlotKind(len(_SlotKind_index)-1) {
		return "SlotKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SlotKind_name[_SlotKind_index[i]:_SlotKind_index[i+1]]
}
